[package]
name = "bevy_rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"

[dev-dependencies]
bevy = { version = "0.9.1", features = ["wayland"]}
bevy-inspector-egui = "0.14.0"